# Generated by Django 5.2 on 2025-05-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
                ("status", models.BooleanField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("config", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("file", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Auth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                (
                    "host_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.host"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                ("port", models.SmallIntegerField()),
                ("status", models.BooleanField()),
                (
                    "host_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.host"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField()),
                (
                    "auth_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="data.auth"
                    ),
                ),
                (
                    "host_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.host"
                    ),
                ),
                (
                    "interface_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="data.interface",
                    ),
                ),
                (
                    "template_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="data.template",
                    ),
                ),
            ],
        ),
    ]
